### PR TITLE
Problem: chain-docs theme cannot show tips

### PR DESCRIPTION
**Pull request by foreseaz**
Add back the new theme and fix the problem of cannot show tips.

### CODE REVIEW

**Review by tomtau — APPROVED** [review]

**Comment by tomtau** [comment]
@foreseaz made it a draft PR, so that it's not accidentally merged

**Comment by foreseaz** [comment]
@tomtau sure, can it be changed later? Since it may need to deploy to production today.

**Comment by tomtau** [comment]
> @tomtau sure, can it be changed later? Since it may need to deploy to production today.

yep, there's a button "Ready for review" which will make it mergeable again

**Pull request merged**
