### PR TITLE
Feature: add options for PDF styling

### PR DESCRIPTION
**Pull request by foreseaz**
[Modify original vuepress plugin](https://github.com/foreseaz/vuepress-plugin-export) to add support of [Puppeteer page.pdf([options])](https://pptr.dev/#?product=Puppeteer&version=v2.1.0&show=api-pagepdfoptions) for PDF's styling, e.g. removing nav bar when generating, can add the surrounding margin, set portrait or landscape, etc.

Usage:
```
[
    "vuepress-plugin-export",
    {
        hideNav: true,
        page: {
            format: 'A4',
            printBackground: true,
            margin: {
                top: 60,
                left: 20,
                right: 20,
                bottom: 60
            }
        }
    }
]
```
Change to `yarn` for package installation, since `npm i` has some issue installing github packages.

Also could resolve issues related to PDF generation: #62 #64

### CODE REVIEW

**Comment by tomtau** [comment]
will https://github.com/crypto-com/chain-docs/blob/master/deploy.sh#L11 still work?

**Comment by foreseaz** [comment]
> will https://github.com/crypto-com/chain-docs/blob/master/deploy.sh#L11 still work?

Should work properly since I only update the flow of PDF generation.

-----

Just tried to deploy to surge, it appears that the build version is missing navbar because the plugin modified the global `context`. I may need a little bit time to fix it.

**Comment by foreseaz** [comment]
@tomtau @lezzokafka Use `deploy.sh` to hack removing the navbar when generating PDF. Already check the deployment. Please review.

**Review by tomtau — APPROVED** [review]
let's see

**Pull request merged**
